# Generated by Django 3.2.9 on 2021-11-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('bio', models.TextField(max_length=12)),
                ('profile_pic', models.FilePathField(path='/img')),
            ],
        ),
    ]
